# Generated by Django 3.1.5 on 2021-01-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210129_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='articles.article'),
        ),
    ]
