# Generated by Django 3.1.5 on 2021-01-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210131_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='articles.article'),
            preserve_default=False,
        ),
    ]
