# Generated by Django 3.1.5 on 2021-02-01 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210131_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='entry',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
