# Generated by Django 3.1.5 on 2021-04-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210202_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='screen',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
